# Generated by Django 5.0.6 on 2024-08-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
