# Generated by Django 5.0.6 on 2024-08-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwq', '0003_alter_blog_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
    ]
