# Generated by Django 5.0.6 on 2024-08-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwq', '0006_remove_blog_author_alter_blog_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='additional_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='additional_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
