# Generated by Django 5.0.6 on 2024-08-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwq', '0008_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_photo',
            field=models.ImageField(blank=True, null=True, upload_to='author_photos/'),
        ),
    ]
